### PR TITLE
Update README links & merge both LICENSE files

### PR DESCRIPTION
**Pull request by Darkilen**
Tweaks:
- Update README links
- Merge both LICENSE files

Reason: (Leave this if it is obvious why from the tweak and/or fix notes)

### CODE REVIEW

**Comment by sekwah41** [comment]
So whats actually changed with the license? I understand the link changes but the license looks a lot shorter

**Comment by sekwah41** [comment]
Because of the nature of the files just merging them isnt the best idea :P

**Comment by Darkilen** [comment]
Sorry, I probably used the wrong term. I didn't merge them, I deleted LICENSE.md and moved LICENSE to LICENSE.md (as you can see in the commit)
What I mean is that I removed an "obsolete duplicate".

**Comment by sekwah41** [comment]
Ahhh thanks for clarifying :)

**Pull request merged**
